### ISSUE TITLE
Where can I find the details of this exploit?

### ISSUE THREAD

**Issue by ultimaweapon** [ChendoChap/pOOBs4#15]
I want to know how it work. Tried to find on Twitter and internet but cannot find any details. The best one I found is just https://twitter.com/notzecoxao/status/1466463051872448521 which I cannot find the details of the exploit.

**Comment by NabilKazi247** [comment]
> any

https://youtu.be/yVFbo23BCK4

**Comment by ultimaweapon** [comment]
Sorry I mean the technical details how exploit work, not the instructions how to jailbreak my PS4.

**Comment by ChendoChap** [comment]
Seeing as this bug is related to an yet to be disclosed h1 entry I've decided to give them the chance to disclose their find themselves (if they get permission). If nothing pops up I might release details later but the bug itself is not an overly complex one, but as for the bare minimum, it is as the name of the repo might give away an out of bounds write that can be exploited under certain conditions.
