### ISSUE TITLE
Blank Trophy timestamps on 9.00

### ISSUE THREAD

**Issue by 44daniel** [ChendoChap/pOOBs4#46]
Hello ChendoChap, my problem is:
recently update from 5.05 to 9.00,aftet I use your web exploit 9.00 but shows 
blank trophy timestamps  with with newer games (GoldHen 2.1.2 and 2.2.2)
how can I solve that?
please,
my model ps4 is CUH-7115B (ps4 pro)

**Comment by ChendoChap** [comment]
Shellcore obtains the trophy timestamps from srtc, the impl. in this repo does not touch anything related to srtc and seeing as you're the first person to bring this up around here it is most likely caused by some other factor(s). 

- do new trophies get a blank timestamp before the kernel has been exploited? -> unrelated to the kernel exploit itself.
- do new trophies only get a blank timestamp when the kernel has been exploited but no payloads have been loaded (such as goldhen) -> it might be related to the exploit itself somehow...
- do new trophies only get a blank timestamp after goldhen has been loaded -> most likely a goldhen issue.

**Comment by 44daniel** [comment]
Test, blank trophy timestamp
-- goldhen 2.0b2 (solved)
--goldhen 2.1.2 (no solved)
--goldhen 2.2.2 (no solved)
The problem is goldhen
